### ISSUE TITLE
Update workflow's that create pull-requests

### ISSUE THREAD

**Issue by andrewvious** [Cloud-Scythe-Labs/reascript-rs#33]
Probably we would want to check if there are changes to commit before trying to open a pull request and exit early if not. Otherwise a branch with no changes and a pull request for that branch will be created.

_Originally posted by @eureka-cpu in https://github.com/Cloud-Scythe-Labs/reascript-rs/pull/31#discussion_r1770643188_

**Comment by eureka-cpu** [comment]
Closing because my follow up comment addresses this
